// Package declaration - this class belongs to the dto package
package com.ecommerce.productservice.dto;

// Import Lombok annotations
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

// Import BigDecimal for price
import java.math.BigDecimal;
// Import LocalDateTime for timestamps
import java.time.LocalDateTime;

/**
 * Product Response DTO (Data Transfer Object)
 *
 * This DTO is used to send product data FROM server TO client
 * Used in API responses for GET requests
 *
 * ProductRequest vs ProductResponse:
 * ----------------------------------
 * ProductRequest (Client → Server):
 * - Used in POST, PUT requests
 * - Contains only editable fields
 * - Has validation annotations
 * - Does NOT include: id, createdAt, updatedAt
 * - Category as ID: categoryId
 *
 * ProductResponse (Server → Client):
 * - Used in GET responses
 * - Contains all fields client should see
 * - No validation annotations (already validated)
 * - INCLUDES: id, createdAt, updatedAt
 * - Category as object: categoryName, categoryId
 *
 * Why include category details?
 * ------------------------------
 * Instead of just categoryId, we include:
 * - categoryId: For reference/filtering
 * - categoryName: For display without additional API call
 *
 * This prevents N+1 query problem:
 * - Bad: Get 100 products, then make 100 API calls to get each category name
 * - Good: Get 100 products with category names included
 *
 * Example API Response:
 * ---------------------
 * GET /api/products/1
 * {
 *   "id": 1,
 *   "name": "Dell XPS 13 Laptop",
 *   "description": "Ultra-thin laptop with 13-inch display",
 *   "price": 1299.99,
 *   "stockQuantity": 50,
 *   "sku": "LAPTOP-DELL-XPS13",
 *   "imageUrl": "https://cdn.example.com/products/dell-xps-13.jpg",
 *   "categoryId": 1,
 *   "categoryName": "Electronics",
 *   "active": true,
 *   "inStock": true,
 *   "createdAt": "2024-01-15T10:30:00",
 *   "updatedAt": "2024-01-20T14:45:00"
 * }
 */

// @Data generates getters, setters, toString, equals, hashCode
@Data

// @NoArgsConstructor generates a no-argument constructor
// Required for Jackson JSON serialization
@NoArgsConstructor

// @AllArgsConstructor generates a constructor with all fields
@AllArgsConstructor

// @Builder enables the Builder pattern for object creation
// Example:
// ProductResponse response = ProductResponse.builder()
//     .id(product.getId())
//     .name(product.getName())
//     .price(product.getPrice())
//     .build();
@Builder
public class ProductResponse {

    /**
     * Product ID
     *
     * Unique identifier generated by the database
     *
     * Why include in response?
     * ------------------------
     * - Client needs it to update product (PUT /api/products/{id})
     * - Client needs it to delete product (DELETE /api/products/{id})
     * - Used as reference in other API calls
     * - Unique key for frontend state management
     *
     * Why NOT accept in request?
     * --------------------------
     * - Server controls ID generation (security)
     * - Prevents ID manipulation attacks
     * - Database auto-increment ensures uniqueness
     */
    private Long id;

    /**
     * Product Name
     *
     * The display name of the product
     *
     * Use cases:
     * ----------
     * - Display in product list
     * - Show in product details page
     * - Use in search results
     * - Display in shopping cart
     * - Show in order history
     *
     * Frontend should:
     * - Truncate long names with ellipsis in lists
     * - Show full name in detail view
     * - Use as page title (SEO)
     */
    private String name;

    /**
     * Product Description
     *
     * Detailed information about the product
     *
     * May be null if no description provided
     *
     * Content typically includes:
     * ---------------------------
     * - Product features
     * - Technical specifications
     * - What's in the box
     * - Warranty information
     * - Usage instructions
     * - Care instructions
     *
     * Frontend handling:
     * ------------------
     * - Display in product details page
     * - Support HTML formatting (if stored as HTML)
     * - Or convert markdown to HTML
     * - Show "No description available" if null
     * - Truncate in list view, full text in detail view
     *
     * SEO benefits:
     * -------------
     * - Rich descriptions improve search ranking
     * - More keywords for product discovery
     * - Better meta descriptions for social sharing
     */
    private String description;

    /**
     * Product Price
     *
     * Current selling price of the product
     *
     * BigDecimal ensures:
     * -------------------
     * - Exact decimal precision (no rounding errors)
     * - Proper monetary calculations
     * - Financial integrity
     *
     * JSON Serialization:
     * -------------------
     * BigDecimal 1299.99 → JSON: 1299.99 (as number)
     * Can be customized to serialize as string: "1299.99"
     *
     * Frontend handling:
     * ------------------
     * - Format with currency symbol: $1,299.99
     * - Format according to locale:
     *   - US: $1,299.99
     *   - EU: €1.299,99
     *   - JP: ¥1,299
     * - Show decimal places even for whole numbers: $100.00 (not $100)
     * - Display sale price separately if applicable
     *
     * Business considerations:
     * ------------------------
     * - Price may change over time
     * - Orders should store snapshot of price at purchase time
     * - Show "Price may vary" disclaimer if real-time pricing
     * - Consider adding salePrice field for discounts
     */
    private BigDecimal price;

    /**
     * Stock Quantity
     *
     * Current available inventory count
     *
     * Business rules:
     * ---------------
     * - > 0: Can be ordered
     * - = 0: Out of stock
     * - Never negative
     *
     * Frontend handling:
     * ------------------
     * Based on quantity, show:
     * - stockQuantity > 50: "In Stock"
     * - stockQuantity 10-50: "Only X left in stock"
     * - stockQuantity 1-9: "Only X left - Order soon!"
     * - stockQuantity = 0: "Out of Stock" + "Notify me" button
     *
     * UI examples:
     * ------------
     * - Green badge: "In Stock" (qty > 50)
     * - Yellow badge: "Low Stock" (qty 1-50)
     * - Red badge: "Out of Stock" (qty = 0)
     * - Show quantity selector limited by stockQuantity
     * - Disable "Add to Cart" if stockQuantity = 0
     *
     * Real-time updates:
     * ------------------
     * - Stock changes when orders are placed
     * - Consider refreshing stock in cart before checkout
     * - Show error if stock insufficient at checkout
     * - Reserve stock during checkout process
     */
    private Integer stockQuantity;

    /**
     * SKU (Stock Keeping Unit)
     *
     * Unique product identifier for inventory management
     *
     * Use cases:
     * ----------
     * - Display in product details (especially for B2B)
     * - Show in invoices and receipts
     * - Use in warehouse operations
     * - Customer support reference
     * - Inventory tracking
     *
     * Frontend display:
     * -----------------
     * - "Product Code: LAPTOP-DELL-XPS13"
     * - "SKU: LAPTOP-DELL-XPS13"
     * - May be hidden in consumer UI
     * - Always visible in admin/business UI
     *
     * Search functionality:
     * ---------------------
     * - Allow searching by SKU
     * - Exact match search (not partial)
     * - Quick lookup for customer service
     */
    private String sku;

    /**
     * Product Image URL
     *
     * URL or path to product image
     *
     * May be null if no image uploaded
     *
     * Frontend handling:
     * ------------------
     * - Display product image in list and detail views
     * - Show placeholder if null:
     *   <img src={imageUrl || '/images/no-image.png'} />
     * - Load thumbnail in list view
     * - Load full size in detail view
     * - Enable image zoom on hover
     * - Image carousel if multiple images (comma-separated)
     *
     * Performance optimization:
     * -------------------------
     * - Lazy load images (load as user scrolls)
     * - Use responsive images (different sizes for different screens)
     * - Add loading placeholder/skeleton
     * - Cache images in browser
     * - Use CDN for faster delivery
     *
     * Multiple images:
     * ----------------
     * If imageUrl contains comma-separated URLs:
     * "img1.jpg,img2.jpg,img3.jpg"
     *
     * Split and display:
     * const images = imageUrl.split(',');
     * images.map(url => <img src={url} />)
     */
    private String imageUrl;

    /**
     * Category ID
     *
     * ID of the category this product belongs to
     *
     * Use cases:
     * ----------
     * - Filter products by category
     * - Navigate to category page
     * - Show related products from same category
     * - Breadcrumb navigation: Home > Electronics > Laptops
     *
     * Frontend usage:
     * ---------------
     * // Get all products in same category
     * GET /api/products?categoryId={categoryId}
     *
     * // Navigate to category page
     * <Link to={`/categories/${categoryId}`}>
     *   {categoryName}
     * </Link>
     */
    private Long categoryId;

    /**
     * Category Name
     *
     * Name of the category (e.g., "Electronics")
     *
     * Why include this?
     * -----------------
     * Convenience field to avoid additional API call
     *
     * Without categoryName:
     * 1. Get product → has categoryId = 1
     * 2. Make another call: GET /api/categories/1
     * 3. Get category name
     * (2 API calls for simple display)
     *
     * With categoryName:
     * 1. Get product → has categoryName = "Electronics"
     * 2. Display directly
     * (1 API call - more efficient)
     *
     * Frontend display:
     * -----------------
     * - Show in product card: "Category: Electronics"
     * - Use in breadcrumbs: "Home > Electronics > Laptops"
     * - Display as tag or badge
     * - Link to category page: <a href="/categories/1">Electronics</a>
     */
    private String categoryName;

    /**
     * Active Status
     *
     * Whether product is currently available for sale
     * - true: Active (visible to customers)
     * - false: Inactive (hidden from customers)
     *
     * Frontend handling:
     * ------------------
     * Customer-facing app:
     * - Only show active = true products
     * - Filter: products.filter(p => p.active)
     *
     * Admin panel:
     * - Show all products with status indicator
     * - Active: Green badge "Active"
     * - Inactive: Red badge "Inactive"
     * - Toggle button to activate/deactivate
     *
     * API filtering:
     * --------------
     * // Customer API - only active products
     * GET /api/products → returns active products only
     *
     * // Admin API - all products
     * GET /api/admin/products → returns all products
     * GET /api/admin/products?active=false → only inactive
     */
    private Boolean active;

    /**
     * In Stock Status (Computed Field)
     *
     * Convenience boolean: true if stockQuantity > 0
     *
     * This is a computed field - not stored in database
     * Calculated from stockQuantity
     *
     * Why include this?
     * -----------------
     * Makes frontend code simpler:
     *
     * Without inStock:
     * if (product.stockQuantity > 0) { ... }
     *
     * With inStock:
     * if (product.inStock) { ... }
     *
     * Calculation in Service layer:
     * ------------------------------
     * response.setInStock(product.getStockQuantity() > 0);
     *
     * Frontend usage:
     * ---------------
     * {inStock ? (
     *   <button>Add to Cart</button>
     * ) : (
     *   <button disabled>Out of Stock</button>
     * )}
     *
     * Filter in-stock products:
     * products.filter(p => p.inStock)
     */
    private Boolean inStock;

    /**
     * Created Timestamp
     *
     * When this product was first added to the catalog
     *
     * Use cases:
     * ----------
     * - Display "Added on: January 15, 2024"
     * - Sort by "New Arrivals" (recent createdAt)
     * - Filter "Products added this week"
     * - Analytics: Track catalog growth
     * - Show "New" badge if < 30 days old
     *
     * Frontend display:
     * -----------------
     * import { formatDistanceToNow } from 'date-fns';
     *
     * // Relative time: "2 days ago"
     * formatDistanceToNow(new Date(createdAt))
     *
     * // Formatted: "January 15, 2024"
     * new Date(createdAt).toLocaleDateString()
     *
     * "New" badge logic:
     * ------------------
     * const isNew = (createdAt) => {
     *   const daysSinceCreation = Math.floor(
     *     (Date.now() - new Date(createdAt)) / (1000 * 60 * 60 * 24)
     *   );
     *   return daysSinceCreation <= 30;
     * };
     */
    private LocalDateTime createdAt;

    /**
     * Updated Timestamp
     *
     * When this product was last modified
     *
     * Use cases:
     * ----------
     * - Display "Last updated: 2 hours ago"
     * - Sort by "Recently updated"
     * - Cache invalidation (refresh if updatedAt changed)
     * - Track price changes history
     * - Admin: See when product was last edited
     *
     * Detecting changes:
     * ------------------
     * if (createdAt === updatedAt) {
     *   // Never modified since creation
     * } else {
     *   // Has been updated
     * }
     *
     * Frontend display:
     * -----------------
     * // Show if recently updated (< 24 hours)
     * const recentlyUpdated = (updatedAt) => {
     *   const hoursSinceUpdate = Math.floor(
     *     (Date.now() - new Date(updatedAt)) / (1000 * 60 * 60)
     *   );
     *   return hoursSinceUpdate <= 24;
     * };
     *
     * if (recentlyUpdated(product.updatedAt)) {
     *   <Badge>Recently Updated</Badge>
     * }
     *
     * Caching strategy:
     * -----------------
     * // Cache product data
     * const cachedProduct = localStorage.getItem('product-1');
     * const cached = JSON.parse(cachedProduct);
     *
     * // Fetch fresh data
     * const fresh = await fetch('/api/products/1').then(r => r.json());
     *
     * // Compare timestamps
     * if (fresh.updatedAt !== cached.updatedAt) {
     *   // Data changed, update cache
     *   localStorage.setItem('product-1', JSON.stringify(fresh));
     * }
     */
    private LocalDateTime updatedAt;

    // =========================================================================
    // Entity to DTO Conversion
    // =========================================================================
    //
    // In Service layer, convert Product entity to ProductResponse:
    //
    // public ProductResponse toResponse(Product product) {
    //     return ProductResponse.builder()
    //         .id(product.getId())
    //         .name(product.getName())
    //         .description(product.getDescription())
    //         .price(product.getPrice())
    //         .stockQuantity(product.getStockQuantity())
    //         .sku(product.getSku())
    //         .imageUrl(product.getImageUrl())
    //         .categoryId(product.getCategory().getId())
    //         .categoryName(product.getCategory().getName())
    //         .active(product.getActive())
    //         .inStock(product.getStockQuantity() > 0)
    //         .createdAt(product.getCreatedAt())
    //         .updatedAt(product.getUpdatedAt())
    //         .build();
    // }
    //
    // =========================================================================
    // JSON Response Example
    // =========================================================================
    //
    // GET /api/products/1
    // HTTP 200 OK
    // Content-Type: application/json
    //
    // {
    //   "id": 1,
    //   "name": "Dell XPS 13 Laptop",
    //   "description": "Ultra-thin laptop with 13-inch 4K display...",
    //   "price": 1299.99,
    //   "stockQuantity": 50,
    //   "sku": "LAPTOP-DELL-XPS13",
    //   "imageUrl": "https://cdn.example.com/products/dell-xps-13.jpg",
    //   "categoryId": 1,
    //   "categoryName": "Electronics",
    //   "active": true,
    //   "inStock": true,
    //   "createdAt": "2024-01-15T10:30:00",
    //   "updatedAt": "2024-01-20T14:45:00"
    // }
}
